// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0hVmgh6xlqReWB33mSSeVBbzi5Q7C9w',
    appId: '1:534967218159:web:617a5fda8df7276fe2901a',
    messagingSenderId: '534967218159',
    projectId: 'mytask-manager-dd01d',
    authDomain: 'mytask-manager-dd01d.firebaseapp.com',
    storageBucket: 'mytask-manager-dd01d.firebasestorage.app',
    measurementId: 'G-25EKPHB043',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYqRGh-LGcwJ82V4aLGxuRw77b247_C8',
    appId: '1:534967218159:android:39c6606f1aadc25ee2901a',
    messagingSenderId: '534967218159',
    projectId: 'mytask-manager-dd01d',
    storageBucket: 'mytask-manager-dd01d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonukdF71RGavD20xnwOGsKUrx1EBjWbc',
    appId: '1:534967218159:ios:ab9bc1c5013347ace2901a',
    messagingSenderId: '534967218159',
    projectId: 'mytask-manager-dd01d',
    storageBucket: 'mytask-manager-dd01d.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDonukdF71RGavD20xnwOGsKUrx1EBjWbc',
    appId: '1:534967218159:ios:ab9bc1c5013347ace2901a',
    messagingSenderId: '534967218159',
    projectId: 'mytask-manager-dd01d',
    storageBucket: 'mytask-manager-dd01d.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq0hVmgh6xlqReWB33mSSeVBbzi5Q7C9w',
    appId: '1:534967218159:web:a81178cb410bb837e2901a',
    messagingSenderId: '534967218159',
    projectId: 'mytask-manager-dd01d',
    authDomain: 'mytask-manager-dd01d.firebaseapp.com',
    storageBucket: 'mytask-manager-dd01d.firebasestorage.app',
    measurementId: 'G-6H6PM4PJM7',
  );
}
