// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGYuxB_G91TnDmSSMpm9N_YzYN2V4CTLw',
    appId: '1:859774840954:web:77c2e14b7b9d911d5a4bc3',
    messagingSenderId: '859774840954',
    projectId: 'task-manager-e8262',
    authDomain: 'task-manager-e8262.firebaseapp.com',
    storageBucket: 'task-manager-e8262.firebasestorage.app',
    measurementId: 'G-6VTF5W4K9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnx9Kx4W-10YUU-4pSFrUo77b6z7-o7B0',
    appId: '1:859774840954:android:81dfab7ad2f9876a5a4bc3',
    messagingSenderId: '859774840954',
    projectId: 'task-manager-e8262',
    storageBucket: 'task-manager-e8262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgJpXCrGz2w2ydSC6ZvjoEUdUq9L0R6G4',
    appId: '1:859774840954:ios:98d8a20aec9487695a4bc3',
    messagingSenderId: '859774840954',
    projectId: 'task-manager-e8262',
    storageBucket: 'task-manager-e8262.firebasestorage.app',
    androidClientId:
        '859774840954-qsej1n291h9vuh33u2bkdd5jmumg73sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgJpXCrGz2w2ydSC6ZvjoEUdUq9L0R6G4',
    appId: '1:859774840954:ios:98d8a20aec9487695a4bc3',
    messagingSenderId: '859774840954',
    projectId: 'task-manager-e8262',
    storageBucket: 'task-manager-e8262.firebasestorage.app',
    androidClientId:
        '859774840954-qsej1n291h9vuh33u2bkdd5jmumg73sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGYuxB_G91TnDmSSMpm9N_YzYN2V4CTLw',
    appId: '1:859774840954:web:3ef97241db17c7215a4bc3',
    messagingSenderId: '859774840954',
    projectId: 'task-manager-e8262',
    authDomain: 'task-manager-e8262.firebaseapp.com',
    storageBucket: 'task-manager-e8262.firebasestorage.app',
    measurementId: 'G-0G2BQ4ZRJH',
  );

}